spring.application.name=testtaskmanager

spring.datasource.url=jdbc:mysql://localhost:3306/task_manager?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=task_user
spring.datasource.password=aEsY5NoE

mybatis.configuration.map-underscore-to-camel-case=true
