@baseUrl = http://localhost:8080
@taskId = 1

### 测试 Spring Boot 是否正常
GET {{baseUrl}}/hello

>>! {{$projectRoot}}/docs/api-responses/crud/01-hello.json


### 新增任务
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "统一返回结构测试任务",
  "description": "用于验证 Result 返回格式"
}

>>! {{$projectRoot}}/docs/api-responses/crud/02-create-task.json


### 查询任务列表
GET {{baseUrl}}/tasks

>>! {{$projectRoot}}/docs/api-responses/crud/03-list-tasks.json


### 根据 ID 查询任务
GET {{baseUrl}}/tasks/{{taskId}}

>>! {{$projectRoot}}/docs/api-responses/crud/04-get-task-by-id.json


### 修改任务状态
PUT {{baseUrl}}/tasks/{{taskId}}/status
Content-Type: application/json

{
  "status": "DONE"
}

>>! {{$projectRoot}}/docs/api-responses/crud/05-update-task-status.json


### 删除任务
DELETE {{baseUrl}}/tasks/{{taskId}}

>>! {{$projectRoot}}/docs/api-responses/crud/06-delete-task.json


### 删除后再次查询任务列表
GET {{baseUrl}}/tasks

>>! {{$projectRoot}}/docs/api-responses/crud/07-list-tasks-after-delete.json
